name: 21f3001224@ds.study.iitm.ac.in

on:
  schedule:
    # Runs daily at 09:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  daily-update:
    runs-on: ubuntu-latest
    name: 21f3001224@ds.study.iitm.ac.in
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "21f3001224@ds.study.iitm.ac.in"

      - name: Make daily update file
        run: |
          echo "Last updated on $(date -u)" > last_update.txt

      - name: Commit changes
        run: |
          git add last_update.txt
          git commit -m "Automated daily commit - $(date -u)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
